= Spring Boot Microservices + Pact-JVM

This project contains a *very simple* demo of using http://martinfowler.com/articles/consumerDrivenContracts.html[consumer-driven contracts] to verify the interactions between microservices.
It leverages http://projects.spring.io/spring-boot[Spring Boot] for both the provider and consumer services.

Testing is achieved using the https://github.com/DiUS/pact-jvm[pact-jvm] project, which is a JVM port of the original https://github.com/realestate-com-au/pact[pact].

== Running the Demo

. Run the tests using Maven:
+
----
$ mvn verify 
----

. This will result in the creation of a https://github.com/realestate-com-au/pact/wiki/Terminology#pact-file[pact file] called `Foo_Consumer-Foo_Provider.json` at `microservices-pact/microservices-pact-consumer/target/pacts`. Here's a current example:
+
----
{
  "provider" : {
    "name" : "Foo_Provider"
  },
  "consumer" : {
    "name" : "Foo_Consumer"
  },
  "interactions" : [ {
    "description" : "a request for Foos",
    "request" : {
      "method" : "GET",
      "path" : "/foos"
    },
    "response" : {
      "status" : 200,
      "headers" : {
        "Content-Type" : "application/json;charset=UTF-8"
      },
      "body" : [ {
        "value" : 42
      }, {
        "value" : 100
      } ]
    }
  } ],
  "metadata" : {
    "pact-specification" : {
      "version" : "2.0.0"
    },
    "pact-jvm" : {
      "version" : "2.1.7"
    }
  }
}
----
+
By virtue of the fact that these tests pass, we know that the `microservices-pact-consumer` app interacts appropriately with the contract as defined in link:microservices-pact-consumer/src/test/java/io/pivotal/microservices/pact/consumer/ConsumerPortTest.java[ConsumerPortTest.java].

In the output of the tests, you should see output along these lines:
----

Verifying a pact between microservice-consumer and microservice-provider
  a request for Foos
    returns a response which
      has status code 200 (OK)
      includes headers
        "Content-Type" with value "application/json;charset=UTF-8" (OK)
      has a matching body (OK)

BUILD SUCCESSFUL
----
